[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  source = "https://github.com/ya-enot/go-amino.git"
  name = "github.com/tendermint/go-amino"
  branch = "ya-enot-v0.11.1"

[[constraint]]
  source = "https://github.com/ya-enot/tendermint.git"
  name = "github.com/tendermint/tendermint"
  branch = "ya-enot-v0.22.8"

[prune]
  go-tests = true
  unused-packages = true
